version: '3'
services:
  db:
    container_name: unico-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./db/data.csv:/tmp/data.csv
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unico-app
    ports:
      - '8000:8000'
    depends_on:
      - db
